apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminservice
  template:
    metadata:
      labels:
        app: adminservice
    spec:
      containers:
        - name: adminservice
          image: adminservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50053
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "auth_user"
            - name: DB_PASSWORD
              value: "vovavova"
            - name: DB_NAME
              value: "auth_db"
            - name: JWT_ACCESS_SECRET
              value: "super-secret-key"
            - name: JWT_REFRESH_SECRET
              value: "super-secret-key-1234321"
---
apiVersion: v1
kind: Service
metadata:
  name: adminservice
spec:
  selector:
    app: adminservice
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
  type: ClusterIP