version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4.2.2-management-alpine
    container_name: ads-rabbitmq
    ports:
      - "${RABBIT_PORT}:5672"
      - "15672:15672" # admin-panel
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
    ports:
      - "${AUTH_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - auth_pg_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: ./authservice/Dockerfile
    container_name: auth-service
    ports:
      - "${AUTH_GRPC_PORT}:${AUTH_GRPC_PORT}"
    depends_on:
      auth-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=${AUTH_DB_USER}
      - DB_PASSWORD=${AUTH_DB_PASSWORD}
      - DB_NAME=${AUTH_DB_NAME}
      - DB_SSL_MODE=${AUTH_DB_SSL_MODE}
      - DB_OPEN_CONNECTIONS=${AUTH_DB_OPEN_CONNECTIONS}
      - DB_IDLE_CONNECTIONS=${AUTH_DB_IDLE_CONNECTIONS}
      - DB_CONNECTION_LIFETIME=${AUTH_DB_CONNECTION_LIFETIME}
      - ACCESS_SECRET=${AUTH_ACCESS_SECRET}
      - REFRESH_SECRET=${AUTH_REFRESH_SECRET}
      - ACCESS_TTL=${AUTH_ACCESS_TTL}
      - REFRESH_TTL=${AUTH_REFRESH_TTL}
      - PASSWORD_COST=${AUTH_PASSWORD_COST}
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - RABBIT_WAIT_TIME=${RABBIT_WAIT_TIME}
      - RABBIT_ATTEMPTS=${RABBIT_ATTEMPTS}
      - EXCHANGE_NAME=${ACCOUNT_EXCHANGE}
      - ROUTING_KEY=${ACCOUNT_ROUTING_KEY}
      - GRPC_PORT=${AUTH_GRPC_PORT}
      - LOG_LEVEL=${AUTH_LOG_LEVEL}
      - ENVIRONMENT=${AUTH_ENVIRONMENT}

  auth-migrations:
    image: migrate/migrate:latest
    container_name: auth-migrations
    volumes:
      - ./authservice/migrations:/migrations
    command:
      - -path=/migrations/
      - -database=postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth-db:5432/${AUTH_DB_NAME}?sslmode=disable
      - up
    depends_on:
      auth-db:
          condition: service_healthy

  user-db:
    image: postgres:15-alpine
    container_name: user-db
    environment:
      - POSTGRES_USER=${USER_DB_USER}
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD}
      - POSTGRES_DB=${USER_DB_NAME}
    ports:
      - "${USER_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_DB_USER} -d ${USER_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - user_pg_data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: ./userservice/Dockerfile
    container_name: user-service
    ports:
      - "${USER_GRPC_PORT}:${USER_GRPC_PORT}"
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USER=${USER_DB_USER}
      - DB_PASSWORD=${USER_DB_PASSWORD}
      - DB_NAME=${USER_DB_NAME}
      - DB_SSL_MODE=${USER_DB_SSL_MODE}
      - DB_OPEN_CONNECTIONS=${USER_DB_OPEN_CONNECTIONS}
      - DB_IDLE_CONNECTIONS=${USER_DB_IDLE_CONNECTIONS}
      - DB_CONNECTION_LIFETIME=${USER_DB_CONNECTION_LIFETIME}
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - RABBIT_WAIT_TIME=${RABBIT_WAIT_TIME}
      - RABBIT_ATTEMPTS=${RABBIT_ATTEMPTS}
      - EXCHANGE_NAME=${ACCOUNT_EXCHANGE}
      - QUEUE_NAME=${USER_SERVICE_QUEUE}
      - ROUTING_KEY=${ACCOUNT_ROUTING_KEY}
      - GRPC_PORT=${USER_GRPC_PORT}
      - LOG_LEVEL=${USER_LOG_LEVEL}
      - ENVIRONMENT=${USER_ENVIRONMENT}

  user-migrations:
    image: migrate/migrate:latest
    container_name: user-migrations
    volumes:
      - ./userservice/migrations:/migrations
    command:
      - -path=/migrations/
      - -database=postgres://${USER_DB_USER}:${USER_DB_PASSWORD}@user-db:5432/${USER_DB_NAME}?sslmode=disable
      - up
    depends_on:
      user-db:
        condition: service_healthy

  ad-db:
    image: postgres:15-alpine
    container_name: ad-db
    environment:
      - POSTGRES_USER=${AD_DB_USER}
      - POSTGRES_PASSWORD=${AD_DB_PASSWORD}
      - POSTGRES_DB=${AD_DB_NAME}
    ports:
      - "${USER_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AD_DB_USER} -d ${AD_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ad_pg_data:/var/lib/postgresql/data

  ad-service:
    build:
      context: .
      dockerfile: .adservice/Dockerfile
    container_name: ad-service

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: ads-gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - AUTH_GRPC_ADDR=auth-service:50051
      - USER_GRPC_ADDR=user-service:50052
    depends_on:
      - auth-service
      - user-service

volumes:
  auth_pg_data:
  user_pg_data: