version: "3.9"

services:
  authservice:
    build:
      context: .
      dockerfile: authservice/Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: auth_user
      DB_PASSWORD: vovavova
      DB_NAME: auth_db
      JWT_ACCESS_SECRET: super-secret-key
      JWT_REFRESH_SECRET: super-secret-key-1234321
    ports:
      - "50051:50051"
    depends_on:
      - db

  userservice:
    build:
      context: .
      dockerfile: userservice/Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: auth_user
      DB_PASSWORD: vovavova
      DB_NAME: auth_db
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB_NAME: ads_service
      MONGODB_BUCKET_NAME: photos
      JWT_ACCESS_SECRET: super-secret-key
      JWT_REFRESH_SECRET: super-secret-key-1234321
    depends_on:
      - db
      - mongo
    ports:
      - "50052:50052"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      AUTH_GRPC_ADDR: authservice:50051
      USER_GRPC_ADDR: userservice:50052

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: vovavova
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
