version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: test_postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports:
      - "5444:5432"