version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4.2.2-management-alpine
    container_name: ads-rabbitmq
    ports:
      - "${RABBIT_PORT}:5672"
      - "15672:15672" # admin-panel
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-pg:
    image: postgres:15-alpine
    container_name: auth-pg
    environment:
      - POSTGRES_USER=${AUTH_PG_USER}
      - POSTGRES_PASSWORD=${AUTH_PG_PASSWORD}
      - POSTGRES_DB=${AUTH_PG_DB_NAME}
    ports:
      - "${AUTH_PG_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_PG_USER} -d ${AUTH_PG_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - auth_pg_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: ./authservice/Dockerfile
    container_name: auth-service
    ports:
      - "${AUTH_GRPC_PORT}:${AUTH_GRPC_PORT}"
    depends_on:
      auth-pg:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DB_HOST=auth-pg
      - DB_PORT=5432
      - DB_USER=${AUTH_PG_USER}
      - DB_PASSWORD=${AUTH_PG_PASSWORD}
      - DB_NAME=${AUTH_PG_DB_NAME}
      - DB_SSL_MODE=${AUTH_PG_SSL_MODE}
      - DB_OPEN_CONNECTIONS=${AUTH_PG_OPEN_CONNECTIONS}
      - DB_IDLE_CONNECTIONS=${AUTH_PG_IDLE_CONNECTIONS}
      - DB_CONNECTION_LIFETIME=${AUTH_PG_CONNECTION_LIFETIME}
      - ACCESS_SECRET=${AUTH_ACCESS_SECRET}
      - REFRESH_SECRET=${AUTH_REFRESH_SECRET}
      - ACCESS_TTL=${AUTH_ACCESS_TTL}
      - REFRESH_TTL=${AUTH_REFRESH_TTL}
      - PASSWORD_COST=${AUTH_PASSWORD_COST}
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - RABBIT_WAIT_TIME=${RABBIT_WAIT_TIME}
      - RABBIT_ATTEMPTS=${RABBIT_ATTEMPTS}
      - EXCHANGE_NAME=${ACCOUNT_EXCHANGE}
      - ROUTING_KEY=${ACCOUNT_ROUTING_KEY}
      - GRPC_PORT=${AUTH_GRPC_PORT}
      - LOG_LEVEL=${AUTH_LOG_LEVEL}
      - ENVIRONMENT=${AUTH_ENVIRONMENT}

  auth-migrations:
    image: migrate/migrate:latest
    container_name: auth-migrations
    volumes:
      - ./authservice/migrations:/migrations
    command:
      - -path=/migrations/
      - -database=postgres://${AUTH_PG_USER}:${AUTH_PG_PASSWORD}@auth-pg:5432/${AUTH_PG_DB_NAME}?sslmode=disable
      - up
    depends_on:
      auth-pg:
          condition: service_healthy

  user-pg:
    image: postgres:15-alpine
    container_name: user-pg
    environment:
      - POSTGRES_USER=${USER_PG_USER}
      - POSTGRES_PASSWORD=${USER_PG_PASSWORD}
      - POSTGRES_DB=${USER_PG_DB_NAME}
    ports:
      - "${USER_PG_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_PG_USER} -d ${USER_PG_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - user_pg_data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: ./userservice/Dockerfile
    container_name: user-service
    ports:
      - "${USER_GRPC_PORT}:${USER_GRPC_PORT}"
    depends_on:
      user-pg:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DB_HOST=user-pg
      - DB_PORT=5432
      - DB_USER=${USER_PG_USER}
      - DB_PASSWORD=${USER_PG_PASSWORD}
      - DB_NAME=${USER_PG_DB_NAME}
      - DB_SSL_MODE=${USER_PG_SSL_MODE}
      - DB_OPEN_CONNECTIONS=${USER_PG_OPEN_CONNECTIONS}
      - DB_IDLE_CONNECTIONS=${USER_PG_IDLE_CONNECTIONS}
      - DB_CONNECTION_LIFETIME=${USER_PG_CONNECTION_LIFETIME}
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - RABBIT_WAIT_TIME=${RABBIT_WAIT_TIME}
      - RABBIT_ATTEMPTS=${RABBIT_ATTEMPTS}
      - EXCHANGE_NAME=${ACCOUNT_EXCHANGE}
      - QUEUE_NAME=${USER_SERVICE_QUEUE}
      - ROUTING_KEY=${ACCOUNT_ROUTING_KEY}
      - GRPC_PORT=${USER_GRPC_PORT}
      - LOG_LEVEL=${USER_LOG_LEVEL}
      - ENVIRONMENT=${USER_ENVIRONMENT}

  user-migrations:
    image: migrate/migrate:latest
    container_name: user-migrations
    volumes:
      - ./userservice/migrations:/migrations
    command:
      - -path=/migrations/
      - -database=postgres://${USER_PG_USER}:${USER_PG_PASSWORD}@user-pg:5432/${USER_PG_DB_NAME}?sslmode=disable
      - up
    depends_on:
      user-pg:
        condition: service_healthy

  ad-pg:
    image: postgres:15-alpine
    container_name: ad-pg
    environment:
      - POSTGRES_USER=${AD_PG_USER}
      - POSTGRES_PASSWORD=${AD_PG_PASSWORD}
      - POSTGRES_DB=${AD_PG_DB_NAME}
    ports:
      - "${AD_PG_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AD_PG_USER} -d ${AD_PG_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ad_pg_data:/var/lib/postgresql/data

  ad-mongo:
    image: mongo:8.2.3-noble
    container_name: ad-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${AD_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${AD_MONGO_PASSWORD}
    ports:
      - "${AD_MONGO_PORT:-27017}:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ad_mongo_data:/data/db

  ad-service:
    build:
      context: .
      dockerfile: adservice/Dockerfile
    container_name: ad-service
    ports:
      - "${AD_GRPC_PORT}:${AD_GRPC_PORT}"
    depends_on:
      ad-pg:
        condition: service_healthy
      ad-mongo:
        condition: service_healthy
    environment:
      - PG_HOST=ad-pg
      - PG_PORT=5432
      - PG_USER=${AD_PG_USER}
      - PG_PASSWORD=${AD_PG_PASSWORD}
      - PG_DB_NAME=${AD_PG_DB_NAME}
      - PG_SSL_MODE=${AD_PG_SSL_MODE}
      - PG_OPEN_CONNECTIONS=${AD_PG_OPEN_CONNECTIONS}
      - PG_IDLE_CONNECTIONS=${AD_PG_IDLE_CONNECTIONS}
      - PG_CONNECTION_LIFETIME=${AD_PG_CONNECTION_LIFETIME}
      - MONGO_HOST=ad-mongo
      - MONGO_PORT=27017
      - MONGO_USER=${AD_MONGO_USER}
      - MONGO_PASSWORD=${AD_MONGO_PASSWORD}
      - MONGO_DB_NAME=${AD_MONGO_DB_NAME}
      - MONGO_COLLECTION_NAME=${AD_MONGO_COLLECTION_NAME}
      - GRPC_PORT=${AD_GRPC_PORT}
      - LOG_LEVEL=${AD_LOG_LEVEL}
      - ENVIRONMENT=${AD_ENVIRONMENT}

  ad-migrations:
    image: migrate/migrate:latest
    container_name: ad-migrations
    volumes:
      - ./adservice/migrations:/migrations
    command:
      - -path=/migrations/
      - -database=postgres://${AD_PG_USER}:${AD_PG_PASSWORD}@ad-pg:5432/${AD_PG_DB_NAME}?sslmode=disable
      - up
    depends_on:
      ad-pg:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: ads-gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - AUTH_GRPC_ADDR=auth-service:50051
      - USER_GRPC_ADDR=user-service:50052
    depends_on:
      - auth-service
      - user-service
      - ad-service

volumes:
  auth_pg_data:
  user_pg_data:
  ad_pg_data:
  ad_mongo_data: